/*****************************************************************************
 * Filename:    display_mipi.h
 *
 * Copyright 2010, Research In Motion Ltd
 *
 * Author:      Victor Chen
 *
 * Created:     July 16, 2010
 *
 * Description: This header file defines structures from MIPI display spec  
 *
 *****************************************************************************/
#ifndef __DISPLAY_MIPI_H__ 
#define __DISPLAY_MIPI_H__ 

/* MIPI DSI Data Type */
typedef enum  
{
    MIPI_DSI_DT_VSYNC_START = 0x01,
    MIPI_DSI_DT_COLOR_MODE_OFF = 0x02,
    /* DCS/Generic short or read */
    MIPI_DSI_DT_GENERIC_SHORT_WRITE_NO_PARAMETER = 0x03,
    MIPI_DSI_DT_GENERIC_READ_NO_PARAMETER = 0x04,
    MIPI_DSI_DT_DCS_SHORT_WRITE_NO_PARAMETER = 0x05,
    MIPI_DSI_DT_DCS_READ_NO_PARAMETER=0x06,
    MIPI_DSI_DT_END_OF_TRANSMISSION_PACKET = 0x08,
    MIPI_DSI_DT_NULL_PACKET = 0x09,
    MIPI_DSI_DT_RGB_565_PACKET=0x0E,    
    MIPI_DSI_DT_VSYNC_END=0x11,
    MIPI_DSI_DT_COLOR_MODE_ON = 0x12,
    MIPI_DSI_DT_GENERIC_SHORT_WRITE_1_PARAMETER = 0x13,
    MIPI_DSI_DT_GENERIC_READ_1_PARAMETER = 0x14,
    MIPI_DSI_DT_DCS_SHORT_WRITE_1_PARAMETER = 0x15,
    MIPI_DSI_DT_BLANKING_PACKET = 0x19,
    MIPI_DSI_DT_RGB_666_PACKET=0x1E,    
    MIPI_DSI_DT_HSYNC_START=0x21,
    MIPI_DSI_DT_SHUT_DOWN_PERIPHERAL = 0x22,
    MIPI_DSI_DT_GENERIC_SHORT_WRITE_2_PARAMETER = 0x23,
    MIPI_DSI_DT_GENERIC_READ_2_PARAMETER = 0x24,
    MIPI_DSI_DT_GENERIC_LONG_WRITE = 0x29,
    MIPI_DSI_DT_RGB_UNPACKED_666_PACKET=0x2E,    
    MIPI_DSI_DT_HSYNC_END=0x31,
    MIPI_DSI_DT_TURN_ON_PERIPHERAL=0x32,
    MIPI_DSI_DT_SET_MAX_RETURN_PACKET_SIZE = 0x37,
    MIPI_DSI_DT_DCS_LONG_WRITE=0x39,
    /*Packed 24-bit RGB */
    MIPI_DSI_DT_RGB_888_PACKET=0x3E,    
}MipiDsiData_t; 

typedef enum  
{ 
    MIPI_DCS_NOP = 0x00, 
    MIPI_DCS_SOFT_RESET = 0x01,
    MIPI_DCS_GET_DISPLAY_ID = 0x04, 
    MIPI_DCS_GET_RED_CHANNEL = 0x06,
    MIPI_DCS_GET_GREEN_CHANNEL = 0x07, 
    MIPI_DCS_GET_BLUE_CHANNEL = 0x08, 
    MIPI_DCS_GET_DISPLAY_STATUS = 0x09, 
    MIPI_DCS_GET_POWER_MODE = 0x0A, 
    MIPI_DCS_GET_ADDRESS_MODE = 0x0B, 
    MIPI_DCS_GET_PIXEL_FORMAT = 0x0C, 
    MIPI_DCS_GET_DISPLAY_MODE = 0x0D,
    MIPI_DCS_GET_SIGNAL_MODE = 0x0E, 
    MIPI_DCS_GET_DIAGNOSTIC_RESULT = 0x0F, 
    MIPI_DCS_ENTER_SLEEP_MODE = 0x10,
    MIPI_DCS_EXIT_SLEEP_MODE = 0x11,
    MIPI_DCS_ENTER_PARTIAL_MODE = 0x12, 
    MIPI_DCS_ENTER_NORMAL_MODE = 0x13,
    MIPI_DCS_EXIT_INVERT_MODE = 0x20,
    MIPI_DCS_ENTER_INVERT_MODE = 0x21, 
    MIPI_DCS_SET_GAMMA_CURVE = 0x26, 
    MIPI_DCS_SET_DISPLAY_OFF = 0x28, 
    MIPI_DCS_SET_DISPLAY_ON = 0x29, 
    MIPI_DCS_SET_COLUMN_ADDRESS = 0x2A, 
    MIPI_DCS_SET_PAGE_ADDRESS = 0x2B, 
    MIPI_DCS_WRITE_MEMORY_START = 0x2C, 
    MIPI_DCS_WRITE_LUT = 0x2D, 
    MIPI_DCS_READ_MEMORY_START = 0x2E, 
    MIPI_DCS_SET_PARTIAL_AREA = 0x30, 
    MIPI_DCS_SET_SCROLL_AREA = 0x33, 
    MIPI_DCS_SET_TEAR_OFF = 0x34, 
    MIPI_DCS_SET_TEAR_ON = 0x35, 
    MIPI_DCS_SET_ADDRESS_MODE = 0x36,
    MIPI_DCS_SET_SCROLL_START = 0x37,
    MIPI_DCS_EXIT_IDLE_MODE = 0x38,
    MIPI_DCS_ENTER_IDLE_MODE = 0x39, 
    MIPI_DCS_SET_PIXEL_FORMAT = 0x3A, 
    MIPI_DCS_WRITE_MEMORY_CONTINUE = 0x3C, 
    MIPI_DCS_READ_MEMORY_CONTINUE = 0x3E,
    MIPI_DCS_SET_TEAR_SCANLINE = 0x44, 
    MIPI_DCS_GET_SCANLINE = 0x45, 
    MIPI_DCS_READ_DDB_START = 0xA1, 
    MIPI_DCS_READ_DDB_CONTINUE = 0xA8, 
}MipiDcsCmd_t;

#define MIPI_DCS_PIXEL_FMT_24BIT 7
#define MIPI_DCS_PIXEL_FMT_18BIT 6 
#define MIPI_DCS_PIXEL_FMT_16BIT 5 
#define MIPI_DCS_PIXEL_FMT_12BIT 3 
#define MIPI_DCS_PIXEL_FMT_8BIT 2 
#define MIPI_DCS_PIXEL_FMT_3BIT 1 

#endif //__DISPLAY_MIPI_H__
